version: "3.1"

services:
  simple_app:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/init.js:/docker-entrypoint-initdb.d/init.js:ro
